spring:
  # 配置数据源信息
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          #url路径
          url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
          #驱动
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password:
          #          type: com.zaxxer.hikari.HikariDataSource #指定驱动类型
        cloud: #第二数据源 别名
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://10.20.252.201:5432/ldb_srm?stringtype=unspecified
          username: etouwa
          password: etouwa@0505
        base-info:
          driver-class: org.postgresql.Driver
          url: jdbc:postgresql://10.20.252.201:5432/basic_info_test?stringtype=unspecified
          username: etouwa
          password: etouwa@0505
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
minio:
  endpoint: http://192.168.100.108:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: bijw